import { useEffect, useState } from 'react';
import { supabase, Ticket } from '../../lib/supabase';
import DataGrid, { Column } from '../../components/DataGrid';

// Extended Ticket type to include joined data
type TicketWithDetails = Ticket & {
  routes?: { name: string };
  boarding_stops?: { name: string };
  destination_stops?: { name: string };
};

export default function TicketsView() {
  const [tickets, setTickets] = useState<TicketWithDetails[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Run cleanup then load
    const init = async () => {
      await autoCancelOldTickets();
      await loadTickets();
    };
    init();
  }, []);

  const autoCancelOldTickets = async () => {
    // Logic: Find entries older than 3 hours that are 'booked'
    const threeHoursAgo = new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString();

    // 1. Get IDs to cancel (limited by RLS, so Admin must have access)
    const { data: expiredTickets } = await supabase
      .from('tickets')
      .select('id')
      .eq('status', 'booked')
      .lt('created_at', threeHoursAgo);

    if (expiredTickets && expiredTickets.length > 0) {
      const ids = expiredTickets.map(t => t.id);
      // 2. Bulk update
      await supabase
        .from('tickets')
        .update({ status: 'cancelled' })
        .in('id', ids);
    }
  };

  const loadTickets = async () => {
    setLoading(true);
    const { data } = await supabase
      .from('tickets')
      .select(`
        *,
        routes(name),
        boarding_stops:stops!tickets_boarding_stop_id_fkey(name),
        destination_stops:stops!tickets_destination_stop_id_fkey(name)
      `)
      .order('created_at', { ascending: false });

    setTickets(data || []);
    setLoading(false);
  };

  const statusColors = {
    booked: 'bg-blue-50 text-blue-700',
    used: 'bg-green-50 text-green-700',
    cancelled: 'bg-red-50 text-red-700',
  };

  const columns: Column<TicketWithDetails>[] = [
    {
      key: 'user_id',
      header: 'Passenger',
      render: (ticket) => (
        <span className="font-medium text-slate-800">
          User #{ticket.user_id.substring(0, 5)}...
        </span>
      ),
    },
    {
      key: 'route',
      header: 'Route',
      render: (ticket) => ticket.routes?.name || 'N/A',
    },
    {
      key: 'seat',
      header: 'Seat',
      render: (ticket) => (
        <span className="bg-slate-100 px-2 py-1 rounded text-xs font-mono">
          1{ticket.id.substring(0, 1)}
        </span>
      ),
    },
    {
      key: 'fare',
      header: 'Fare',
      render: () => '₹250',
    },
    {
      key: 'trip',
      header: 'Trip Details',
      render: (ticket) => (
        <div className="flex flex-col">
          <span className="text-xs text-slate-400">From: {ticket.boarding_stops?.name}</span>
          <span className="text-xs text-slate-400">To: {ticket.destination_stops?.name}</span>
        </div>
      ),
    },
    {
      key: 'booking_date',
      header: 'Date',
      render: (ticket) => new Date(ticket.booking_date).toLocaleDateString(),
    },
    {
      key: 'status',
      header: 'Status',
      render: (ticket) => (
        <span className={`text-xs px-2 py-1 rounded font-medium ${statusColors[ticket.status as keyof typeof statusColors] || 'bg-slate-100 text-slate-600'}`}>
          {ticket.status.toUpperCase()}
        </span>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 tracking-tight">Ticket Bookings</h1>
          <p className="text-slate-500">Monitor all user bookings in real-time.</p>
        </div>
        <button
          onClick={loadTickets}
          className="px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 transition text-sm font-medium shadow-sm"
        >
          Refresh List
        </button>
      </div>

      <DataGrid
        columns={columns}
        data={tickets}
        loading={loading}
        title="Recent Bookings"
        description="List of all tickets generated by the system."
        onSearch={(term) => console.log('Search:', term)}
      />
    </div>
  );
}
